2021-11-29 15:30:38,685 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-11-29 15:37:15,048 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-11-29 15:38:21,469 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-11-29 16:02:17,353 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-11-29 16:16:26,117 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-11-29 16:17:37,188 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-11-29 16:20:05,081 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-11-29 16:34:37,720 ERROR: Exception on /result [GET] [in c:\users\hanco\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\hanco\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\hanco\moovietribe\app\main\routes.py", line 170, in result
    if item.moovie_id == moovie.id:
AttributeError: 'NoneType' object has no attribute 'id'
2021-12-01 07:15:36,410 ERROR: Exception on /result [GET] [in c:\users\hanco\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\hanco\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\hanco\moovietribe\app\main\routes.py", line 170, in result
    if item.moovie_id == moovie.id:
AttributeError: 'NoneType' object has no attribute 'id'
2021-12-01 07:34:28,254 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:36:35,123 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:38:23,054 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:39:56,556 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:42:52,910 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:44:00,222 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:44:41,790 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:44:59,986 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:45:25,785 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:46:00,403 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:46:29,451 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:46:48,960 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 07:48:05,242 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 08:04:01,313 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-01 08:04:08,649 ERROR: Exception on /add_moovie [GET] [in c:\users\hanco\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\hanco\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\hanco\moovietribe\app\main\routes.py", line 105, in add_moovie
    return render_template('add_moovie.html', title=_('Search'), form=form)
  File "c:\users\hanco\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\hanco\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\hanco\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\hanco\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\hanco\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\hanco\moovietribe\app\templates\add_moovie.html", line 2, in top-level template code
    {% import 'bootstrap/form.html' as wtf %}
  File "C:\Users\hanco\moovietribe\app\templates\base.html", line 173, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Users\hanco\moovietribe\app\templates\add_moovie.html", line 9, in block "app_content"
    2) Please use the full title exactly as it appears on IMDB.  You can check the title by clicking <a class="btn btn-outline-success" href="{{ url_for('https://www.imdb.com/') }}">HERE</a>.
  File "c:\users\hanco\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\hanco\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\hanco\venv\lib\site-packages\werkzeug\routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'https://www.imdb.com/'. Did you mean 'static' instead?
2021-12-01 08:05:08,133 INFO: Microblog startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
