2021-12-02 20:40:24,153 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 16:19:28,923 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 16:50:20,275 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 16:51:22,611 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 16:59:56,699 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:02:22,100 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:04:34,950 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:05:18,534 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:09:15,002 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:11:36,587 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:23:55,810 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:25:55,206 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-04 17:28:42,806 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-05 09:47:16,060 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-05 10:44:05,833 ERROR: Exception on /chatspace [POST] [in c:\users\hanco\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\hanco\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\hanco\moovietribe\app\main\routes.py", line 248, in chatspace
    post.chat_count = post.chat_count + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2021-12-05 10:46:59,797 ERROR: Exception on /chatspace [GET] [in c:\users\hanco\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\hanco\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\hanco\moovietribe\app\main\routes.py", line 257, in chatspace
    if item.moovie_id == moovie.id:
AttributeError: 'NoneType' object has no attribute 'id'
2021-12-05 10:48:03,168 ERROR: Exception on /chatspace [GET] [in c:\users\hanco\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hanco\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hanco\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\hanco\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\hanco\moovietribe\app\main\routes.py", line 257, in chatspace
    if item.moovie_id == moovie.id:
AttributeError: 'NoneType' object has no attribute 'id'
2021-12-05 10:54:43,557 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-06 17:53:53,560 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-06 18:20:54,040 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-06 18:27:44,829 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-06 18:29:26,328 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-06 18:49:39,113 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
2021-12-08 13:47:45,157 INFO: MoovieTribe startup [in C:\Users\hanco\moovietribe\app\__init__.py:82]
